### ISSUE TITLE
三级路由情况下，切换一级路由，默认重定向不会触发

### ISSUE THREAD

**Issue by ChanHaiWei** [Vgbire/react-route-cache#10]
<img width="959" alt="企业微信截图_1732700388393" src="https://github.com/user-attachments/assets/492cbfa6-0acb-4be2-a38e-84aa15f642be">

<img width="1292" alt="企业微信截图_17327005896518" src="https://github.com/user-attachments/assets/1345caa8-03a0-418d-9df1-fa4cd10fc8ea">

**Comment by Vgbire** [comment]
@ChanHaiWei 临时解决办法：把设置了index: true的路由和父路由cache都设置为false，后续修复一下这个问题
![image](https://github.com/user-attachments/assets/db376e62-1709-461a-ba30-59f38375746c)

**Comment by Vgbire** [comment]
fixed
