### ISSUE TITLE
KeepAlive的max属性有逻辑有问题，缓存10个页面当到第11个的时候不会清除第1个缓存而且清除了所有缓存页面，重新缓存

### ISSUE THREAD

**Issue by ChanHaiWei** [Vgbire/react-route-cache#12]
<img width="959" alt="d4d4f718fa94038d60870b4fcf6f1ae" src="https://github.com/user-attachments/assets/e849398a-3872-4f19-9843-ce164fffd630">

期望效果，缓存10个页面，当到第11个页面时，清除的是第一个页面，依次类推

**Comment by Vgbire** [comment]
fixed
