### ISSUE TITLE
RouterTabs不支持修改配色

### ISSUE THREAD

**Issue by ChanHaiWei** [Vgbire/react-route-cache#2]
项目架构：react18+antd pro+router v6

项目主色：#0d141d

期望效果：希望tab能使用antd的tabs，这样我就可以基于antd的ConfigProvider组件进行全局切换主题

![image](https://github.com/user-attachments/assets/b10e98e3-a125-47b1-9980-72544f93899b)

**Comment by Vgbire** [comment]
> 项目架构：react18+antd pro+router v6
> 
> 项目主色：#0d141d
> 
> 期望效果：希望tab能使用antd的tabs，这样我就可以基于antd的ConfigProvider组件进行全局切换主题
> 
> ![image](https://private-user-images.githubusercontent.com/56662636/384794787-b10e98e3-a125-47b1-9980-72544f93899b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDQ0MTUsIm5iZiI6MTczMTMwNDExNSwicGF0aCI6Ii81NjY2MjYzNi8zODQ3OTQ3ODctYjEwZTk4ZTMtYTEyNS00N2IxLTk5ODAtNzI1NDRmOTM4OTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA1NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOGM1NGI4ZWQ5NWI2OTZhOTc3M2IyMTYxNmEzNzIwMjRhOTZlZDVhYzExMmFhYzY5MGEyYzlhZjY3OTAwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EhdUi2blKVbssCdrAADLT2IqQD3ZanbMxsTMcgstkBE)

左侧用的是antd menu 的 黑色主题吗

**Comment by ChanHaiWei** [comment]
> > 项目架构：react18+antd pro+router v6
> > 项目主色：#0d141d
> > 期望效果：希望tab能使用antd的tabs，这样我就可以基于antd的ConfigProvider组件进行全局切换主题
> > ![image](https://private-user-images.githubusercontent.com/56662636/384794787-b10e98e3-a125-47b1-9980-72544f93899b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDQ0MTUsIm5iZiI6MTczMTMwNDExNSwicGF0aCI6Ii81NjY2MjYzNi8zODQ3OTQ3ODctYjEwZTk4ZTMtYTEyNS00N2IxLTk5ODAtNzI1NDRmOTM4OTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA1NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOGM1NGI4ZWQ5NWI2OTZhOTc3M2IyMTYxNmEzNzIwMjRhOTZlZDVhYzExMmFhYzY5MGEyYzlhZjY3OTAwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EhdUi2blKVbssCdrAADLT2IqQD3ZanbMxsTMcgstkBE)
> 
> 左侧用的是antd menu 的 黑色主题吗

使用的是antd黑色主题，主色调是自己配置的token，这一套架构是antd pro的Layout组件

**Comment by Vgbire** [comment]
fixed closed
