### ISSUE TITLE
 height: 100%; 无法传递给子页面，outlet中的页面无法拿到父组件的height: 100%

### ISSUE THREAD

**Issue by ChanHaiWei** [Vgbire/react-route-cache#3]
<div style={{ height: '100%' }}>
        <KeepAliveScope>
             <RouterTabs />
             <KeepAlive>{outlet}</KeepAlive>
        </KeepAliveScope>
</div>

outlet中的页面无法拿到父组件的height: 100%

这导致outlet中的div需要拿vh去计算减去RouterTabs的高度，加上NavMenu的高度，才能拿到outlet的可可滚动高度

期望效果：outlet中的页面也拿到父组件传递下来的100%高度

![image](https://github.com/user-attachments/assets/a7b72630-790a-44dc-9949-bf410b5a60d8)

**Comment by Vgbire** [comment]
fixed
